import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Plus, Pencil, Trash2, Printer, MessageCircle, Upload, FileSpreadsheet } from "lucide-react";
import { toast } from "sonner";
import { printReport } from "@/lib/print-report";
import { whatsappLink } from "@/lib/documents";
import { parseReceptionExcel, type ReceptionImportRow, type ReceptionImportError } from "@/lib/reception-import";

export const Route = createFileRoute("/_authenticated/recepcao")({ head: () => ({ meta: [{ title: "Recepção - Gestão Judicial" }, { name: "description", content: "Registro de atendimentos da recepção: data, advogado, cliente, CPF, telefone e atendente." }, { property: "og:title", content: "Recepção - Gestão Judicial" }, { property: "og:description", content: "Cadastre e consulte os atendimentos recebidos na recepção." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: RecepcaoPage });

type Reception = { id: string; data: string; advogado: string; nome_cliente: string; cpf: string | null; telefone: string; atendente: string; created_at: string };
const emptyForm = { data: new Date().toISOString().slice(0, 10), advogado: "", nome_cliente: "", cpf: "", telefone: "", atendente: "" };
function br(d: string) { if (!d) return "—"; const [y, m, dd] = d.split("-"); return `${dd}/${m}/${y}`; }

function RecepcaoPage() {
  const qc = useQueryClient(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Reception | null>(null); const [form, setForm] = useState({ ...emptyForm }); const [saving, setSaving] = useState(false); const [toDelete, setToDelete] = useState<Reception | null>(null); const [busca, setBusca] = useState("");
  const [importOpen, setImportOpen] = useState(false); const [importRows, setImportRows] = useState<ReceptionImportRow[]>([]); const [importErrors, setImportErrors] = useState<ReceptionImportError[]>([]); const [importing, setImporting] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const { data: rows = [], isLoading } = useQuery({ queryKey: ["reception-entries"], queryFn: async () => { const { data, error } = await supabase.from("reception_entries").select("*").order("data", { ascending: false }).order("created_at", { ascending: false }); if (error) throw error; return data as Reception[]; } });
  const filtered = useMemo(() => { const q = busca.trim().toLowerCase(); if (!q) return rows; return rows.filter(r => [r.nome_cliente, r.advogado, r.atendente, r.cpf ?? "", r.telefone].some(v => v.toLowerCase().includes(q))); }, [rows, busca]);
  function openNew() { setEditing(null); setForm({ ...emptyForm }); setOpen(true); }
  function openEdit(r: Reception) { setEditing(r); setForm({ data: r.data, advogado: r.advogado, nome_cliente: r.nome_cliente, cpf: r.cpf ?? "", telefone: r.telefone, atendente: r.atendente }); setOpen(true); }
  async function save() { if (!form.nome_cliente.trim()) return toast.error("Informe o nome do cliente"); if (!form.telefone.trim()) return toast.error("Informe o telefone"); if (!form.advogado.trim()) return toast.error("Informe o advogado"); if (!form.atendente.trim()) return toast.error("Informe o atendente"); setSaving(true); try { const payload = { data: form.data, advogado: form.advogado.trim(), nome_cliente: form.nome_cliente.trim(), cpf: form.cpf.trim() || null, telefone: form.telefone.trim(), atendente: form.atendente.trim() }; if (editing) { const { error } = await supabase.from("reception_entries").update(payload).eq("id", editing.id); if (error) throw error; toast.success("Registro atualizado"); } else { const { data: auth } = await supabase.auth.getUser(); const { error } = await supabase.from("reception_entries").insert({ ...payload, created_by: auth.user?.id ?? null }); if (error) throw error; toast.success("Atendimento registrado"); } setOpen(false); qc.invalidateQueries({ queryKey: ["reception-entries"] }); } catch (e) { toast.error("Erro ao salvar", { description: e instanceof Error ? e.message : "" }); } finally { setSaving(false); } }
  async function confirmDelete() { if (!toDelete) return; const { error } = await supabase.from("reception_entries").delete().eq("id", toDelete.id); if (error) toast.error("Erro ao excluir", { description: error.message }); else { toast.success("Registro excluído"); qc.invalidateQueries({ queryKey: ["reception-entries"] }); } setToDelete(null); }
  function printOne(r: Reception) { printReport({ title: "Registro de Recepção", subtitle: r.nome_cliente, sections: [{ heading: "Dados do atendimento", columns: ["Campo", "Informação"], rows: [["Data", br(r.data)], ["Advogado", r.advogado], ["Nome do cliente", r.nome_cliente], ["CPF", r.cpf || "—"], ["Telefone", r.telefone], ["Atendente", r.atendente]] }] }); }
  function printList() { printReport({ title: "Recepção — Registros de Atendimento", subtitle: `${filtered.length} registro(s)`, sections: [{ columns: ["Data", "Advogado", "Nome do cliente", "CPF", "Telefone", "Atendente"], rows: filtered.map(r => [br(r.data), r.advogado, r.nome_cliente, r.cpf || "—", r.telefone, r.atendente]) }] }); }
  async function chooseImport(file?: File) { if (!file) return; try { const result = await parseReceptionExcel(file); setImportRows(result.rows); setImportErrors(result.errors); setImportOpen(true); } catch (e) { toast.error("Não foi possível ler a planilha", { description: e instanceof Error ? e.message : "Arquivo inválido" }); } finally { if (fileRef.current) fileRef.current.value = ""; } }
  async function confirmImport() { if (!importRows.length) return; setImporting(true); try { const { data: auth } = await supabase.auth.getUser(); const payload = importRows.map(r => ({ ...r, created_by: auth.user?.id ?? null })); const { error } = await supabase.from("reception_entries").insert(payload); if (error) throw error; toast.success(`${importRows.length} registro(s) importado(s) com sucesso`); setImportOpen(false); setImportRows([]); setImportErrors([]); qc.invalidateQueries({ queryKey: ["reception-entries"] }); } catch (e) { toast.error("Erro ao importar", { description: e instanceof Error ? e.message : "Não foi possível salvar os registros" }); } finally { setImporting(false); } }

  return <div className="min-w-0 space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h1 className="text-xl font-semibold text-foreground sm:text-2xl">Recepção</h1><p className="text-sm text-muted-foreground">Registro de atendimentos recebidos na recepção.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => fileRef.current?.click()} className="flex-1 sm:flex-none"><Upload className="mr-2 h-4 w-4" /> Importar Excel</Button><Button variant="outline" onClick={printList} className="flex-1 sm:flex-none"><Printer className="mr-2 h-4 w-4" /> Imprimir lista</Button><Button onClick={openNew} className="flex-1 sm:flex-none"><Plus className="mr-2 h-4 w-4" /> Novo registro</Button><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e => void chooseImport(e.target.files?.[0])} /></div></div>
    <Input placeholder="Buscar por cliente, advogado, atendente, CPF ou telefone" value={busca} onChange={e => setBusca(e.target.value)} />
    <Card><CardHeader className="pb-2"><CardTitle className="text-base">Atendimentos ({filtered.length})</CardTitle></CardHeader><CardContent className="p-0 sm:p-6 sm:pt-0">{isLoading ? <p className="p-4 text-sm text-muted-foreground">Carregando...</p> : filtered.length === 0 ? <p className="p-4 text-sm text-muted-foreground">Nenhum registro encontrado.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="p-2">Data</th><th className="p-2">Advogado</th><th className="p-2">Nome do cliente</th><th className="p-2">CPF</th><th className="p-2">Telefone</th><th className="p-2">Atendente</th><th className="p-2 text-right">Ações</th></tr></thead><tbody>{filtered.map(r => <tr key={r.id} className="border-b last:border-0"><td className="p-2 whitespace-nowrap">{br(r.data)}</td><td className="p-2">{r.advogado}</td><td className="p-2 font-medium">{r.nome_cliente}</td><td className="p-2">{r.cpf || "—"}</td><td className="p-2 whitespace-nowrap"><a href={whatsappLink(r.telefone)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline"><MessageCircle className="h-4 w-4" />{r.telefone}</a></td><td className="p-2">{r.atendente}</td><td className="p-2"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" title="Editar" onClick={() => openEdit(r)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" title="Excluir" onClick={() => setToDelete(r)}><Trash2 className="h-4 w-4 text-destructive" /></Button><Button size="icon" variant="ghost" title="Imprimir" onClick={() => printOne(r)}><Printer className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] w-[calc(100vw-2rem)] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{editing ? "Editar registro" : "Novo registro de atendimento"}</DialogTitle><DialogDescription>Preencha os dados do atendimento da recepção.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Data</Label><Input type="date" value={form.data} onChange={e => setForm({ ...form, data: e.target.value })} /></div><div className="space-y-1.5"><Label>Advogado</Label><Input value={form.advogado} onChange={e => setForm({ ...form, advogado: e.target.value })} /></div><div className="space-y-1.5 sm:col-span-2"><Label>Nome do cliente</Label><Input value={form.nome_cliente} onChange={e => setForm({ ...form, nome_cliente: e.target.value })} /></div><div className="space-y-1.5"><Label>CPF</Label><Input value={form.cpf} onChange={e => setForm({ ...form, cpf: e.target.value })} /></div><div className="space-y-1.5"><Label>Telefone</Label><Input value={form.telefone} onChange={e => setForm({ ...form, telefone: e.target.value })} /></div><div className="space-y-1.5 sm:col-span-2"><Label>Atendente</Label><Input value={form.atendente} onChange={e => setForm({ ...form, atendente: e.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving ? "Salvando..." : "Salvar"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={v => !importing && setImportOpen(v)}><DialogContent className="max-h-[85vh] w-[calc(100vw-2rem)] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><FileSpreadsheet className="h-5 w-5" /> Prévia da importação</DialogTitle><DialogDescription>Formato: Data | Advogado | Nome do cliente | CPF | Telefone | Atendente.</DialogDescription></DialogHeader><div className="space-y-3"><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-md border p-3"><div className="text-xs text-muted-foreground">Válidos</div><div className="text-lg font-semibold">{importRows.length}</div></div><div className="rounded-md border p-3"><div className="text-xs text-muted-foreground">Com erro</div><div className="text-lg font-semibold">{importErrors.length}</div></div><div className="rounded-md border p-3"><div className="text-xs text-muted-foreground">Total processado</div><div className="text-lg font-semibold">{importRows.length + importErrors.length}</div></div></div>{importErrors.length > 0 && <div className="max-h-32 overflow-auto rounded-md border p-3 text-sm"><p className="font-medium">Linhas que não serão importadas:</p>{importErrors.map(e => <div key={e.line}>Linha {e.line}: {e.message}</div>)}</div>}{importRows.length > 0 && <div className="max-h-72 overflow-auto rounded-md border"><table className="w-full text-sm"><thead className="sticky top-0 bg-background"><tr className="border-b text-left"><th className="p-2">Data</th><th className="p-2">Advogado</th><th className="p-2">Cliente</th><th className="p-2">CPF</th><th className="p-2">Telefone</th><th className="p-2">Atendente</th></tr></thead><tbody>{importRows.map((r, i) => <tr key={`${r.nome_cliente}-${i}`} className="border-b last:border-0"><td className="p-2">{br(r.data)}</td><td className="p-2">{r.advogado}</td><td className="p-2">{r.nome_cliente}</td><td className="p-2">{r.cpf || "—"}</td><td className="p-2">{r.telefone}</td><td className="p-2">{r.atendente}</td></tr>)}</tbody></table></div>}</div><DialogFooter><Button variant="outline" onClick={() => setImportOpen(false)} disabled={importing}>Cancelar</Button><Button onClick={confirmImport} disabled={!importRows.length || importing}>{importing ? "Importando..." : `Confirmar importação (${importRows.length})`}</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={!!toDelete} onOpenChange={v => !v && setToDelete(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir registro?</AlertDialogTitle><AlertDialogDescription>Esta ação não pode ser desfeita. O atendimento será removido permanentemente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={confirmDelete}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
